#Site settings
title: All About Life.
description: A blog about Life Matters.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Urgyen Shakya 
user_description: All ABout Life

user_title: Software Developer | Trek Guide
email: urgyenshakya@gmail.com
#twitter_username: lorem_ipsum
github_username:  https://github.com/urgyen
fb_username:  https://www.facebook.com/urgyen777




# Google-analytics
google-analytics:
  id: ""



exclude: ['package.json', 'src' , 'node_modules']
