#Site settings
title: All About Life.
description: A blog about Life Matters.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Urgyen Shakya 
user_description: CS undergrad, wanting to Travel.
user_title: Thik thik.
email: urgyenshakya@gmail.com

github_username:  https://github.com/urgyen
fb_username:  https://www.facebook.com/urgyen777



exclude: ['package.json', 'src' , 'node_modules']
